---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cs-deployment
  namespace: broomfield
  labels:
    app: cloudflare-sync
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudflare-sync
  template:
    metadata:
      labels:
        app: cloudflare-sync
    spec:
      containers:
        - name: syncer
          image: cr.r3t.io/library/cloudflare-sync:latest
          env:
            - name: RECORDS_FILE_NAME
              value: /opt/production.json
            - name: ZONE_ID
              value: "1e0dc3689be892462939bf419b0ba58d"
            - name: API_TOKEN
              value: "PTMLsDx8RJ3Ddmo6tUApKOH8CeiZ19KJfS0xIn47"
            - name: FREQUENCY
              value: "30"
          volumeMounts:
            - mountPath: /opt/production.json
              subPath: production.json
              name: config
      volumes:
        - name: config
          configMap:
            name: cs-config
            items:
              - key: production.json
                path: production.json
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cs-config
  namespace: broomfield
data:
  production.json: |
    [
      {
        "type": "A",
        "name": "r3t.io",
        "proxied": true,
        "ttl": 120,
        "priority": 1
      },
      {
        "type": "A",
        "name": "cr.r3t.io",
        "proxied": false,
        "ttl": 120,
        "priority": 1
      },
      {
        "type": "A",
        "name": "blog.r3t.io",
        "proxied": true,
        "ttl": 120,
        "priority": 1
      },
      {
        "type": "A",
        "name": "vpn.r3t.io",
        "proxied": false,
        "ttl": 120,
        "priority": 1
      },
      {
        "type": "A",
        "name": "ci.r3t.io",
        "proxied": true,
        "ttl": 120,
        "priority": 1
      },
      {
        "type": "A",
        "name": "airport.r3t.io",
        "proxied": false,
        "ttl": 120,
        "priority": 1
      }
    ]
